on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Go Release

permissions:
    contents: write
    packages: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Get last changelog entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2.2.2
        with:
          version: ${{ steps.previoustag.outputs.tag }}
          path: ./CHANGELOG.md
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          draft: false
          prerelease: false
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    needs: release
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64,arm64]
    steps:
    - uses: actions/checkout@v2
    - name: Set APP_VERSION env
      run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
    - name: Set BUILD_TIME env
      run: echo BUILD_TIME=$(date) >> ${GITHUB_ENV}
    - uses: wangyoucao577/go-release-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: tcm
        ldflags: "-s -w -X 'main.appVersion=${{ env.APP_VERSION }}' -X 'main.buildTime=${{ env.BUILD_TIME }}' -X 'main.gitCommit=${{ github.sha }}'"
        extra_flags: -trimpath
        md5sum: false
        sha256sum: true
        extra_files: LICENSE README.md CHANGELOG.md
